### ISSUE TITLE
TODO.md

### ISSUE THREAD

**Issue by rafaelnwitter** [rafaelnwitter/movies-api#1]
## Features
- [ ] Create user roles
- [ ] Manage permission to change your created movies

## Fix
- [ ] Fix swagger documentation
- [ ] Create documentation to all functions
